---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Radiating Truthiness: Authenticity performances in politics in Brazil and the United States

This repository makes publicly available all the replication materials for the article "Radiating Truthiness: Authenticity performances in politics in Brazil and the United States". The article is forthcoming in Political Studies, please check it out!

[Henrique](http://henriquesposito.com/) is a PhD Candidate in International Relations and Political Sciences and affiliated to the Centre for International Environmental Studies.

If you are using this any of the replication materials including the data, codes, models, or figures, please cite:

Sposito, Henrique. "Radiating Truthiness: Authenticity performances in politics in Brazil and the United States". *Political Studies* (2024)

### Addditional Materials

For additional information on the data collection, cleaning, and other replication materials please request access to the Authenticity Performances Private repository on GitHub.
